version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hpx
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    environment:
      - RAILS_ENV=development
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:

